# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WordChangeProject' do
 pod 'AFNetworking'
 pod 'SDWebImage'
 pod ‘MJExtension’
 pod ’SVProgressHUD’
 pod ’MJRefresh’
 pod ‘FLAnimatedImage’
 pod ‘YYWebImage’
 pod ’DACircularProgress’
 pod ‘IDMPhotoBrowser’
end
